---
blank_issues_enabled: false
contact_links:
  - name: Taiwan Bus Search Community Support
    url: https://github.com/kayac_chang/Where would you like to go today?/discussions
    about: Please ask and answer questions here.
